### ISSUE TITLE
Hello,I got a question!

### ISSUE THREAD

**Issue by Zero-coder** [wanghq21/MICN#1]
![1677549724005](https://user-images.githubusercontent.com/54145971/221733771-c76fce89-18be-45d4-a6cd-0172ea2b74c7.png)

I haven't see the pooling operation in the local part.Is this unnecessary?Thank you for your inspiring work.

**Comment by Zero-coder** [comment]
I mean no pooling operation in the code.

**Comment by wanghq21** [comment]
![image](https://user-images.githubusercontent.com/32741441/221750377-a65483ef-85ca-4407-8026-e2cf2ed4f181.png)


Hello!
The pooling operation is here ( _153: self.decomp_ ). Of course, to be more standardized, the pooling operation should be located within function _conv_trans_conv_. And it is necessary because we think the different kernels of the pooling operation can represent the different temporal patterns obtained by decomposition. That's where the _multi-scale_ comes from. 

Thanks for your question.

**Comment by Zero-coder** [comment]
got it! Thank U！
